export const authenticationStatus = {
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_EMAIL_PASSWORD: 'INVALID_EMAIL_PASSWORD',
  SOMETHING_WENT_WRONG: 'SOMETHING_WENT_WRONG',
  INVALID_USER: 'INVALID_USER',
  USERNAME_EXISTS: 'USERNAME_EXISTS',
  USERNAME_DOESNOT_EXISTS: 'USERNAME_DOESNOT_EXISTS',
}
