export const ADD_ITEM_PRODUCT_UPLOAD = 'ADD_ITEM_PRODUCT_UPLOAD'
export const REMOVE_ITEM_PRODUCT_UPLOAD = 'REMOVE_ITEM_PRODUCT_UPLOAD'

export const ADD_ITEM_CART = 'ADD_ITEM_CART'
export const INCREMENT_CART_ITEM = 'INCREMENT_CART_ITEM'
export const DECREMENT_CART_ITEM = 'DECREMENT_CART_ITEM'
export const REMOVE_ITEM_CART = 'REMOVE_ITEM_CART'
export const CLEAR_CART = 'CLEAR_CART'

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const STORE_ALL_PRODUCTS = 'STORE_ALL_PRODUCTS'
export const ERROR_FETCHING_PRODUCTS = 'ERROR_FETCHING_PRODUCTS'
